apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # <-- You can specify or let Kubernetes choose
