
name: Deploy to Kubernetes (via Bastion)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my-website
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
      - name: Setup SSH for bastion connection
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/bastion_key
          chmod 600 ~/.ssh/bastion_key
      - name: Copy Kubernetes manifests to bastion
        run: |
          scp -i ~/.ssh/bastion_key -o StrictHostKeyChecking=no  k8s/namespace.yaml k8s/deployment.yaml k8s/service.yaml k8s/ingress.yaml ubuntu@${{ secrets.BASTION_HOST }}:/tmp/
      - name: Deploy to Kubernetes via bastion
        run: |
          ssh -i ~/.ssh/bastion_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_HOST }} << 'EOF'
            set -e
            
            echo "SSH connection successful!"
            echo "Kubernetes cluster status:"
            kubectl get nodes
            
            echo "Applying Kubernetes manifests..."
            kubectl apply -f /tmp/namespace.yaml
            kubectl apply -f /tmp/deployment.yaml
            kubectl apply -f /tmp/service.yaml
            kubectl apply -f /tmp/ingress.yaml
            
            echo "Checking deployment status..."
            kubectl rollout status deployment/$(kubectl get deployment -o name | head -n1 | cut -d'/' -f2) --timeout=120s
            
            # Clean up temporary files
            rm -f /tmp/deployment.yaml /tmp/service.yaml /tmp/ingress.yaml /tmp/namespace.yaml
            echo "✅ Deployment completed successfully!"
          EOF
      - name: Verify Deployment and Check Namespace Content
        run: |
          ssh -i ~/.ssh/bastion_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_HOST }} << 'EOF'
          
          echo "=== DEPLOYMENT VERIFICATION ==="
          
          echo "1. Checking all resources in website namespace:"
          kubectl get all -n website
          
          echo ""
          echo "2. Detailed pod information:"
          kubectl get pods -n website -o wide
          
          echo ""
          echo "3. Service details:"
          kubectl describe service my-website-service -n website
          
          echo ""
          echo "4. Ingress details:"
          kubectl get ingress -n website
          kubectl describe ingress my-website-ingress -n website
          
          echo ""
          echo "5. Deployment status:"
          kubectl describe deployment my-website -n website
          
          echo ""
          echo "6. Pod logs (first pod):"
          POD_NAME=$(kubectl get pods -n website -l app=my-website -o jsonpath='{.items[0].metadata.name}')
          kubectl logs -n website $POD_NAME
          
          echo ""
          echo "7. Service endpoints:"
          kubectl get endpoints -n website
          
          echo ""
          echo "8. Events in website namespace:"
          kubectl get events -n website --sort-by=.lastTimestamp
          
          echo ""
          echo "9. Resource utilization:"
          kubectl top pods -n website
          
          echo ""
          echo "=== VERIFICATION COMPLETE ==="
          
          EOF